//! Text rendering for Peel.
//!
//! The same 8x8 glyph set the kernel console uses, rendered here at a chosen
//! scale. Generated by tools/fontconv and original to this project.

const gfx = @import("gfx.zig");
const glyphs = @import("glyphs.zig");

pub const CHAR_W: i32 = 8;
pub const CHAR_H: i32 = 8;

pub fn drawChar(s: *const gfx.Surface, c: u8, x: i32, y: i32, scale: i32, color: gfx.Color) void {
    const g = glyphs.glyph(c);

    var row: i32 = 0;
    while (row < CHAR_H) : (row += 1) {
        const bits = g[@intCast(row)];
        var col: i32 = 0;
        while (col < CHAR_W) : (col += 1) {
            if (bits & (@as(u8, 0x80) >> @intCast(col)) == 0) continue;
            s.fill(.{
                .x = x + col * scale,
                .y = y + row * scale,
                .w = scale,
                .h = scale,
            }, color);
        }
    }
}

pub fn drawText(s: *const gfx.Surface, text: []const u8, x: i32, y: i32, scale: i32, color: gfx.Color) void {
    var cx = x;
    for (text) |c| {
        drawChar(s, c, cx, y, scale, color);
        cx += CHAR_W * scale;
    }
}

pub fn textWidth(text: []const u8, scale: i32) i32 {
    return @as(i32, @intCast(text.len)) * CHAR_W * scale;
}
